export const CREATEUSER_LOADING = "CREATEUSER_LOADING";
export const CREATEUSER_ERROR = "CREATEUSER_ERROR";
export const CREATEUSER_SUCCESS = "CREATEUSER_SUCCESS";


export const LOGINUSER_LOADING = "LOGINUSER_LOADING";
export const LOGINUSER_ERROR = "LOGINUSER_ERROR";
export const LOGINUSER_SUCCESS = "LOGINUSER_SUCCESS";